"""create news tabel

Revision ID: 5d79f86ba86c
Revises: 4f5e525b2c31
Create Date: 2025-06-17 23:39:12.428828

"""
from typing import Sequence, Union

import fastapi_utils.guid_type
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d79f86ba86c'
down_revision: Union[str, None] = '4f5e525b2c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('user_id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category_id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_news_category_id_categories')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_news_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    op.create_unique_constraint(op.f('uq_categories_id'), 'categories', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_categories_id'), 'categories', type_='unique')
    op.drop_table('news')
    # ### end Alembic commands ###
