"""create categories table

Revision ID: 4f5e525b2c31
Revises: 42e801d9e8a1
Create Date: 2025-06-17 18:39:54.805427

"""
from typing import Sequence, Union

import fastapi_utils.guid_type
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f5e525b2c31'
down_revision: Union[str, None] = '42e801d9e8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', fastapi_utils.guid_type.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('id', name=op.f('uq_categories_id')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_table('categories')
    # ### end Alembic commands ###
